#pragma once
/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'GameHunt'
*/

/* 15204 */
class IGameClientBase
{
public:
	virtual void Initialize(void* a1, void* a2, void* a3); // 0x0-0x8
	virtual void Destroy(); // 0x8-0x10
	virtual void zxy(); // 0x10-0x18
	virtual bool GetMessageData(char** data, unsigned int* len); // 0x18-0x20
	virtual void zzx(); // 0x20-0x28
	virtual void OnIntegrityViolation(void * a1, __int64 a2, void* a3); // 0x28-0x30
	virtual void xyz(); // 0x30-0x38
	virtual void xxz(); // 0x38-0x40
	virtual void yxx(); // 0x40-0x48
	virtual void yxz(); // 0x48-0x50
	virtual void xzy(void* a1, void* a2); // 0x50-0x58
};

/* 749 */
enum InitProgressResult
{
	InitContinue = 0x0,
	InitCancel = 0x1,
};

/* 750 */
enum EACAsyncResult
{
	InitSuccess = 0x0,
	LauncherInvalidParameter = 0x1,
	LauncherDNSError = 0x2,
	LauncherNetworkError = 0x3,
	LauncherFailure = 0x4,
	LauncherInstallError = 0x5,
	LauncherSuccessUnderWine = 0x6,
	InitCancelRequested = 0x7,
	GameClientConnected = 0x8,
	GameClientDisconnected = 0x9,
	GameClientAuthenticated = 0xA,
	GameClientIntegrityViolation = 0xB,
};
